### ISSUE TITLE
Ausgang 2 in Statistikfunktionen hat keine Funktion wenn gleicher Typ wie Ausgang 1

### ISSUE THREAD

**Issue by SirUli** [recomedia/x1-logic-nodes#3]
Hi Horst,

Wenn ich die Funktion für den Ausgang 2 in dem Baustein "Statistikfunktionen" auf die gleiche Funktion wie Ausgang 1 festlege (z.b. beide auf "Mittelwert"), so verschwindet der Ausgang 2 auf dem Baustein. Nehme ich einen anderen, so erscheint er wieder.

Nichts was man nicht anders lösen kann aber vielleicht ja auch eher nicht so beabsichtigt ;)

Viele Grüße,
Uli

**Comment by SirUli** [comment]
Ich sehe gerade dass dies möglicherweise sogar absicht ist - dann wäre es sozusagen eher ein Dokumentationsthema ;) Bei der Inbetriebnahme kommt 

```
Level: Error:Der Baustein "Statistikfunktionen" hat folgendes Problem festgestellt: Die Funktion für Ausgang 2 kann nicht dieselbe sein wie für Ausgang 1"
```

falls das noch angewählt ist.

**Comment by recomedia** [comment]
Ja, das ist so beabsichtigt. Die Dokumentation sollte aber verbessert werden.

**Comment by recomedia** [comment]
Die verbesserte Dokumentation ist in [commit 6e924e13](https://github.com/recomedia/x1-logic-nodes/commit/6e924e13250e5e84140e7fe11bc717e0a43537b4), Version 1.3.11 und höher, eingeflossen. Einen externen release gibt es bisher nicht, weil sonst seit Version 1.3.10 keine Änderungen waren.
